<?php
declare(strict_types=1);
require_once __DIR__.'/../app/bootstrap.php';
require_once __DIR__.'/DeterministicEvaluator.php';
use ODLab\{ResearchContract,EquationSet,Benchmark,LabEngine,DeepSeekClient,Evaluator,MemoryDistribution};
use ODLabTests\DeterministicEvaluator;
$pass=0;$fail=[];function hcheck(bool $ok,string $name):void{global$pass,$fail;if($ok){echo"PASS $name\n";$pass++;}else{$fail[]=$name;echo"FAIL $name\n";}}
try{
    try{EquationSet::mixture(1.2,.5);hcheck(false,'mixture rejects rho > 1');}catch(Throwable){hcheck(true,'mixture rejects rho > 1');}
    try{$x=ResearchContract::defaults();$x['od']['anchor_weight']=1;ResearchContract::validate($x);hcheck(false,'hard-anchor benchmark rejects fake soft anchor slider');}catch(Throwable){hcheck(true,'hard-anchor benchmark rejects fake soft anchor slider');}
    try{$x=ResearchContract::defaults();$x['provider']['base_url']='https://evil.example';ResearchContract::validate($x);hcheck(false,'BYOK provider endpoint cannot be redirected by client config');}catch(Throwable){hcheck(true,'BYOK provider endpoint cannot be redirected by client config');}
    $cfg=ResearchContract::validate(ResearchContract::defaults());
    $coverage=ResearchContract::mathCoverage();$byId=[];foreach($coverage as $m)$byId[$m['id']]=$m;
    hcheck(($byId['eq19']['status']??'')==='exact'&&($byId['eq9_11']['status']??'')==='not_claimed'&&($byId['eq12']['status']??'')==='exact'&&($byId['eq18']['status']??'')==='exact','math coverage distinguishes exact runtime equations from nonclaims');
    foreach(['smoke','core','h2','h3','h5','all','custom'] as $suite){foreach(ResearchContract::conditions($suite,$cfg) as $c)if(($c['mix']??[])!==[])EquationSet::assertProbabilityVector($c['mix']);hcheck(true,"all $suite condition mixtures valid");}
    $b=new Benchmark($cfg['benchmark']);
    $knownIds=[];foreach(['external_train','target_dev','commit_check','candidate_pool','final_known'] as $n)$knownIds=array_merge($knownIds,array_column($b->splits[$n],'id'));hcheck(!array_intersect($knownIds,array_column($b->sealedFinalAbsent(),'id')),'final absent isolated from every known split');
    $sealed=$b->sealedFinalAbsent()[0];try{$b->evaluationEmbedding($sealed);hcheck(false,'sealed absent factor excluded from generator novelty representation');}catch(Throwable){hcheck(true,'sealed absent factor excluded from generator novelty representation');}
    $src=$b->splits['external_train'][0];$synthetic=$b->makeSynthetic($src['factors'],'recombination',[$b->splits['external_train'][0]['id'],$b->splits['external_train'][1]['id']]);hcheck($b->oracleValid($synthetic),'oracle validity independent of candidate-pool membership');

    $ev=new DeterministicEvaluator();$engine=new LabEngine($b,$cfg,$ev);$smoke=ResearchContract::conditions('smoke',$cfg)[1];$r=$engine->runCondition($smoke,101);
    $ad=array_values(array_filter($r['assessments'],fn($a)=>$a['admitted']));$sum=array_sum(array_column($ad,'weight'));hcheck(abs($sum-1.0)<1e-9,'admitted relative weights sum to one');$qh=$r['equation_trace']['eq8_qhat']??[];hcheck($qh===[]||abs(array_sum(array_column($qh,'weight'))-1.0)<1e-9,'logged Eq8 Q-hat remains normalized');hcheck(count(array_filter($r['assessments'],fn($a)=>!$a['admitted']&&$a['weight']!=0.0))===0,'rejected candidates have zero learning weight');
    // Appendix C.2: a normalized softmax can never rescue an inadmissible singleton.
    $singleBad=[['candidate_uid'=>'bad','experience_id'=>'bad','admitted'=>false,'reasons'=>['mandatory_check_failed'],'novelty'=>1.0,'coherence'=>0.0,'anchor'=>1.0,'score'=>999.0,'weight'=>0.0]];
    hcheck(EquationSet::empiricalDistribution($singleBad)===[],'Appendix C.2 reject-all branch precedes relative weighting');
    hcheck(($r['equation_trace']['eq18_tv_bound']['bound_pass']??false)===true,'Eq18 bound verified for engine proposal');
    $rec=array_values(array_filter($r['candidates'],fn($c)=>($c['provenance']['production_operator']??'')==='recombination'));$recOk=true;foreach($rec as $c)if($b->isExternallyObserved($c['id'])||count(array_unique($c['provenance']['source_ids']??[]))<2)$recOk=false;hcheck($recOk,'recombination kernel produces withheld conjunctions with multi-source lineage');
    hcheck(count(array_unique(array_map(fn($a)=>(string)$a['coherence'],$r['assessments'])))>1,'coherence cost is operational, not hardcoded zero');
    $splits=array_column($ev->events(),'split');hcheck($splits===['retention_reference','commit_check_reference','retention_proposal','commit_check_proposal','final_known','final_absent'],'sealed final tests occur only after proposal gate inputs');
    $tev=new DeterministicEvaluator();$tr=(new LabEngine($b,$cfg,$tev))->runCondition(ResearchContract::conditions('h5',$cfg)[1],105);$ts=array_column($tev->events(),'split');$finalPos=array_search('final_known',$ts,true);$targetPos=array_search('target_dev_targeting',$ts,true);hcheck($targetPos!==false&&$finalPos!==false&&$targetPos<$finalPos&&!in_array('final_absent',array_slice($ts,0,$finalPos),true),'H5 targeting uses development data and never sealed final data');hcheck(($tr['equation_trace']['fixed_api_state']['reference']['aux']['targeting']['enabled']??false)===true,'H5 targeting controller variable captured in sufficient-state specialization');

    foreach(ResearchContract::conditions('h2',$cfg) as $cond){$e=new DeterministicEvaluator();$eng=new LabEngine($b,$cfg,$e);$row=$eng->runCondition($cond,101);[$lo,$hi]=$cond['novelty_band'];$ok=true;foreach($row['assessments'] as $a)if($a['admitted']&&($a['novelty']<$lo-1e-12||$a['novelty']>$hi+1e-12))$ok=false;hcheck($ok,"H2 {$cond['name']} admission obeys novelty band");hcheck($row['learning_novelty_mean']===null||($row['learning_novelty_mean']>=$lo-1e-12&&$row['learning_novelty_mean']<=$hi+1e-12),"H2 {$cond['name']} weighted learning novelty in band");}

    $refClass=new ReflectionClass(LabEngine::class);$admit=$refClass->getMethod('admit');$bad=$b->makeSynthetic($src['factors'],'recombination',[$b->splits['external_train'][0]['id'],$b->splits['external_train'][1]['id']]);$bad['label']='WRONG|WRONG|WRONG|WRONG';$memory=array_slice($b->splits['external_train'],0,12);$ar=$admit->invoke($engine,$bad,$smoke,$memory);hcheck(!$ar['admitted']&&in_array('oracle_or_structure_failed',$ar['reasons'],true),'absolute admission rejects bad anchor regardless of ranking');

    $regressionEvaluator=new class implements Evaluator{
        private array $u=['api_calls'=>0,'input_tokens'=>0,'output_tokens'=>0,'latency_seconds'=>0.0];private array $e=[];
        public function usage():array{return$this->u;}public function events():array{return$this->e;}
        public function evaluate(array $memory,array $records,string $split):array{$this->u['api_calls']++;$bad=(bool)array_filter($memory,fn($m)=>($m['provenance']['historical_origin']??'')==='synthetic');$ans=[];$correct=0;foreach($records as $r){$pred=$bad?'WRONG':$r['label'];$ok=$pred===$r['label'];$correct+=(int)$ok;$ans[]=[$r['id'],$pred,$r['label'],$ok];}$this->e[]=['split'=>$split,'success'=>true];return['accuracy'=>count($records)?$correct/count($records):0,'correct'=>$correct,'n'=>count($records),'answers'=>$ans,'usage'=>$this->u];}
    };
    $eng2=new LabEngine($b,$cfg,$regressionEvaluator);$forced=['name'=>'forced_recomb','mix'=>['replay'=>0.0,'recombination'=>1.0,'counterfactual'=>0.0]];$rr=$eng2->runCondition($forced,101);hcheck($rr['gate_status']==='failed'&&$rr['rollback'],'gate failure triggers rollback');hcheck($rr['state_hash_before']===$rr['state_hash_committed']&&$rr['state_hash_proposed']!==$rr['state_hash_committed'],'rollback restores exact reference state');
    $no=$eng2->runCondition(ResearchContract::conditions('smoke',$cfg)[0],102);hcheck($no['gate_status']==='not_applicable_no_change'&&!$no['rollback']&&$no['state_hash_before']===$no['state_hash_committed'],'reject/no-offline path is explicit no-change, not false gate pass');

    $provider=$cfg['provider'];$provider['max_retries']=1;$calls=0;
    $transport=function($url,$headers,$body,$timeout)use(&$calls){$calls++;if($calls===1)return['{"error":"temporary"}',500,''];$ids=[];$content=[];foreach(($body['messages']??[]) as $m){if(($m['role']??'')==='user'&&preg_match('/QUESTIONS \([^)]*\):\\n(.*?)\\nReturn json\\./s',$m['content'],$mm)){$q=json_decode($mm[1],true)?:[];foreach($q as $x)$ids[$x['id']]='UNKNOWN';}}$env=['id'=>'mock-ds','usage'=>['prompt_tokens'=>11,'completion_tokens'=>7],'choices'=>[['finish_reason'=>'stop','message'=>['content'=>json_encode(['answers'=>$ids])]]]];return[json_encode($env),200,''];};
    $budget=['max_api_calls'=>10,'max_input_tokens'=>100000,'max_output_tokens'=>100000];$ds=new DeepSeekClient($provider,'test-key',$budget,$transport);$record=['id'=>'q1','factors'=>['shape'=>'orb','color'=>'amber','position'=>'north','texture'=>'plain'],'label'=>'UNKNOWN','provenance'=>[]];$out=$ds->evaluate([],[$record],'transport_test');hcheck($out['accuracy']==1.0&&$ds->usage()['api_calls']===2,'DeepSeek client retries and parses JSON output');hcheck(count($ds->events())===2&&!$ds->events()[0]['success']&&$ds->events()[1]['success'],'DeepSeek call-level retry evidence retained');
    $strictProvider=$provider;$strictProvider['max_retries']=0;
    $partialTransport=function($url,$headers,$body,$timeout){$env=['id'=>'partial','usage'=>['prompt_tokens'=>5,'completion_tokens'=>3],'choices'=>[['finish_reason'=>'stop','message'=>['content'=>json_encode(['answers'=>['q1'=>'UNKNOWN']])]]]];return[json_encode($env),200,''];};
    $record2=$record;$record2['id']='q2';
    try{(new DeepSeekClient($strictProvider,'test-key',['max_api_calls'=>5,'max_input_tokens'=>100000,'max_output_tokens'=>100000],$partialTransport))->evaluate([],[$record,$record2],'partial');hcheck(false,'missing model answers are evaluator failures, not silently scored wrong');}catch(Throwable){hcheck(true,'missing model answers are evaluator failures, not silently scored wrong');}
    $lengthTransport=function(){return[json_encode(['id'=>'cut','usage'=>['prompt_tokens'=>5,'completion_tokens'=>3],'choices'=>[['finish_reason'=>'length','message'=>['content'=>json_encode(['answers'=>['q1'=>'UNKNOWN']])]]]]),200,''];};
    try{(new DeepSeekClient($strictProvider,'test-key',['max_api_calls'=>5,'max_input_tokens'=>100000,'max_output_tokens'=>100000],$lengthTransport))->evaluate([],[$record],'length');hcheck(false,'truncated DeepSeek completion is rejected');}catch(Throwable){hcheck(true,'truncated DeepSeek completion is rejected');}
    $badBudget=['max_api_calls'=>1,'max_input_tokens'=>100000,'max_output_tokens'=>100000];$calls2=0;$transport2=function()use(&$calls2){$calls2++;return['{}',200,''];};try{(new DeepSeekClient($provider,'test-key',$badBudget,$transport2))->evaluate([],[$record],'budget');hcheck(false,'budget fail-closed before unsafe call');}catch(Throwable){hcheck($calls2===0,'budget fail-closed before unsafe call');}
}catch(Throwable $e){$fail[]='exception: '.$e->getMessage();echo'EXCEPTION '.$e->getMessage()."\n";}
echo"\nHOSTILE PASS $pass\n";if($fail){echo"HOSTILE FAIL ".count($fail)."\n- ".implode("\n- ",$fail)."\n";exit(1);}echo"HOSTILE FAIL 0\n";
