<?php
declare(strict_types=1);
require_once __DIR__.'/../app/bootstrap.php';
require_once __DIR__.'/DeterministicEvaluator.php';
require_once __DIR__.'/TestRepository.php';
use ODLab\{ResearchContract,EquationSet,Benchmark,LabEngine,LabService,Util,MemoryDistribution,RNG};
use ODLabTests\{DeterministicEvaluator,TestRepository};
$pass=0;$fail=[];function check(bool $ok,string $name):void{global$pass,$fail;if($ok){echo"PASS $name\n";$pass++;}else{$fail[]=$name;echo"FAIL $name\n";}}
try{
 $cfg=ResearchContract::validate(ResearchContract::defaults());
 foreach([[0,0],[0.5,0],[0.5,1],[1,0.5],[0.66,0.5],[1,1]] as [$rho,$cf]){$m=EquationSet::mixture($rho,$cf);check(abs(array_sum($m)-1)<1e-12,"mixture rho=$rho cf=$cf");}
 $w=EquationSet::gibbsWeights([1,2,3],0.35);check(abs(array_sum($w)-1)<1e-12&&$w[2]>$w[1]&&$w[1]>$w[0],'gibbs normalized/order');
 $mix=EquationSet::mixture(.6,.25);$rrng=new RNG(12345);$draws=array_fill_keys(['replay','recombination','counterfactual'],0);for($i=0;$i<10000;$i++)$draws[EquationSet::sampleMixtureOperator($mix,$rrng)]++;check(abs($draws['replay']/10000-$mix['replay'])<.03&&abs($draws['recombination']/10000-$mix['recombination'])<.03&&abs($draws['counterfactual']/10000-$mix['counterfactual'])<.03,'Eq3 iid categorical sampler tracks mixture probabilities');
 $ass=[['candidate_uid'=>'a','experience_id'=>'x','admitted'=>true,'weight'=>.25,'novelty'=>.2],['candidate_uid'=>'b','experience_id'=>'y','admitted'=>true,'weight'=>.75,'novelty'=>.6],['candidate_uid'=>'c','experience_id'=>'z','admitted'=>false,'weight'=>0.0,'novelty'=>1.0]];
 $qh=EquationSet::empiricalDistribution($ass);check(count($qh)===2&&abs(array_sum(array_column($qh,'weight'))-1)<1e-12,'Eq8 empirical distribution explicit/normalized');
 $nd=EquationSet::noveltyDiagnostics($ass);check(abs($nd['proposal_novelty']-.6)<1e-12&&abs($nd['learning_novelty']-.5)<1e-12&&abs($nd['admission_fraction']-(2/3))<1e-12,'Eq20 novelty/admission/influence exact');
 check(EquationSet::gate(.8,.76,.7,.66,.05,.05),'gate tolerance pass');check(!EquationSet::gate(.8,.70,.7,.66,.05,.05),'gate regression fail');
 check(EquationSet::lossGate(['retention'=>.2,'check'=>.3],['retention'=>.24,'check'=>.34],['retention'=>.05,'check'=>.05]),'Eq13 native loss gate pass');
 check(EquationSet::accuracyGate(.8,.76,.7,.66,.05,.05)===EquationSet::lossGate(['retention'=>.2,'check'=>.3],['retention'=>.24,'check'=>.34],['retention'=>.05,'check'=>.05]),'accuracy gate is exact L=1-accuracy specialization');
 $b=new Benchmark($cfg['benchmark']);check(count($b->splits['external_train'])===36&&count($b->sealedFinalAbsent())===20,'benchmark split sizes');$b->assertIsolation();check(strlen($b->splitHash)===64,'split hash');
 $ref=MemoryDistribution::uniform(array_slice($b->splits['external_train'],0,2));$syn=$b->makeSynthetic($b->splits['candidate_pool'][0]['factors'],'ordinary_augmentation',[],'declared_label_preserving_rule');$q=MemoryDistribution::uniform([$syn]);$mu=MemoryDistribution::mixture($ref,$q,.3);$tv=MemoryDistribution::verifyMixtureBound($ref,$q,$mu,.3);check($tv['bound_pass']&&abs($tv['tv_proposal_reference']-$tv['rhs'])<1e-12,'Eq12/18 finite-memory mixture and TV identity exact');
 $x=$b->splits['external_train'][0];$phi=$b->evaluationEmbedding($x);check(abs(EquationSet::finiteReferenceNovelty($phi,[$phi],$b->noveltyScale(),$b->noveltyCap()))<1e-12,'Eq19 identical reference novelty zero');
 $f=$x['factors'];$alts=array_values(array_filter(ResearchContract::KNOWN['shape'],fn($v)=>$v!==$f['shape']));$f['shape']=$alts[0];$x1=$b->makeSynthetic($f,'counterfactual',[$x['id']],'shape');$n1=EquationSet::finiteReferenceNovelty($b->evaluationEmbedding($x1),[$phi],$b->noveltyScale(),$b->noveltyCap());check(abs($n1-.5)<1e-12,'Eq19 one categorical mismatch equals 0.5 under declared phi/sigma');
 $ev=new DeterministicEvaluator();$engine=new LabEngine($b,$cfg,$ev);$condition=ResearchContract::conditions('smoke',$cfg)[1];$r=$engine->runCondition($condition,101);check(isset($r['gate_status'],$r['candidates'],$r['assessments']),'engine result structure');check(count(array_unique(array_column($r['candidates'],'candidate_uid')))===count($r['candidates']),'candidate UID uniqueness');check((float)$r['final_absent_accuracy']===0.0,'absent factor remains non-inferable in deterministic evaluator');check(($r['equation_trace']['eq18_tv_bound']['bound_pass']??false)===true,'engine runtime verifies Eq18 bound');check(($r['equation_trace']['eq3_4']['sampling']??'')==='iid_categorical_operator_draws','engine logs iid Eq3 mixture sampling law');check(isset($r['evaluation_evidence']['final_known']['answers'])&&count($r['evaluation_evidence']['final_known']['answers'])===40,'answer-level final evaluation evidence retained');check(($r['equation_trace']['eq12_memory']['eta_cap']??null)===1.0,'Eq12 eta_bar specialization is explicit');
 $cfgEta0=$cfg;$cfgEta0['od']['memory_replace_fraction']=0.0;$engEta0=new LabEngine($b,$cfgEta0,new DeterministicEvaluator());$rEta0=$engEta0->runCondition($condition,103);check($rEta0['no_change']&&$rEta0['no_change_reason']==='eta_zero'&&$rEta0['state_hash_before']===$rEta0['state_hash_proposed'],'eta=0 yields exact Eq12 no-change even with admitted candidates');
 $h5cond=ResearchContract::conditions('h5',$cfg)[1];$rH5=(new LabEngine($b,$cfg,new DeterministicEvaluator()))->runCondition($h5cond,104);check(isset($rH5['equation_trace']['fixed_api_state']['reference']['aux']['targeting'])&&$rH5['equation_trace']['fixed_api_state']['reference']['aux']['targeting']['enabled']===true,'targeting controller state is captured in h_k specialization');
 $repo=new TestRepository();$svc=new LabService($repo,fn($c)=>new DeterministicEvaluator($c['provider']));$smoke=$cfg;$smoke['suite']='smoke';$smoke['seeds']=[101];$id=$svc->createMission(1,'Qualification smoke','End-to-end service test',$smoke);$out=$svc->runMission($id);$run=$svc->getRun($out['run_id']);check($run!==null&&$run['status']==='completed','service mission completes');check(count($run['analysis']['rows'])===2,'condition results persisted');check(count($run['condition_evidence'])===2&&isset($run['condition_evidence'][1]['result']['assessments'],$run['condition_evidence'][1]['result']['evaluation_evidence']),'raw condition and answer-level evaluation evidence persisted');check(count($run['events'])>=5,'research events persisted');check(strlen($run['config_hash'])===64&&strlen($run['split_hash'])===64&&strlen($run['code_manifest_hash'])===64,'research hashes persisted');
 $core=$cfg;$core['suite']='core';$p=$svc->previewConfig($core);check($p['condition_count']===7,'core comparator count');check($p['estimated_api_calls']['baseline']>0,'API call estimate');
 $h2=$cfg;$h2['suite']='h2';$h2['seeds']=[101,102];$id2=$svc->createMission(1,'H2 qualification','Novelty bands',$h2);$o2=$svc->runMission($id2);$rr=$svc->getRun($o2['run_id']);check(count($rr['analysis']['h2']['points'])>=3,'H2 evidence points');check(isset($rr['analysis']['h2']['models']['status']),'H2 model diagnostics');
}catch(Throwable $e){$fail[]='exception: '.$e->getMessage();echo'EXCEPTION '.$e->getMessage()."\n";}
echo"\nTOTAL PASS $pass\n";if($fail){echo"TOTAL FAIL ".count($fail)."\n- ".implode("\n- ",$fail)."\n";exit(1);}echo"TOTAL FAIL 0\n";
