<?php
declare(strict_types=1);
require_once __DIR__.'/../app/bootstrap.php';require_login();header('Cache-Control: no-store, private');
$svc=new ODLab\LabService();$missions=$svc->listMissions();$defaults=ODLab\ResearchContract::defaults();$preview=$svc->previewConfig($defaults);$mix=$preview['mix'];$math=$preview['math_coverage'];
$js=ODLab\I18n::js(['preflight.conditions','preflight.calls','preflight.validating','preflight.valid','preflight.retry_margin','preflight.insufficient','preflight.invalid','api.key_missing','run.running','run.done','run.open_report','run.package','run.failed']);
function lang_switch():string{$l=lang();return '<div class="langswitch" aria-label="'.e(t('lang.switch')).'"><a '.($l==='fr'?'class="active" ':'').'href="'.e(lang_url('fr')).'">FR</a><a '.($l==='en'?'class="active" ':'').'href="'.e(lang_url('en')).'">EN</a></div>';}
function slider(string $labelKey,string $tipKey,string $id,string $value,string $min,string $max,string $step,?string $dataKey=null):string{$data=$dataKey!==null?' data-key="'.e($dataKey).'"':'';return '<div class="slider"><label class="slider-label"><span class="labeltext">'.e(t($labelKey)).' '.info_tip($tipKey).'</span><output>'.e($value).'</output></label><input id="'.e($id).'"'.$data.' type="range" min="'.e($min).'" max="'.e($max).'" step="'.e($step).'" value="'.e($value).'"></div>';}
?><!doctype html><html lang="<?=e(lang())?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><link rel="stylesheet" href="assets/app.css"><title>OD Lab · Mission Control</title></head><body data-csrf="<?=e($_SESSION['csrf'])?>"><header><div><strong>OD Lab</strong><span>Oneiric Dynamics · PHP/MySQL · v<?=ODLAB_VERSION?></span></div><nav><a href="#mission"><?=e(t('nav.new_mission'))?></a><a href="#runs"><?=e(t('nav.labs'))?></a><a href="#api"><?=e(t('nav.api'))?></a><a href="health.php"><?=e(t('nav.health'))?></a><?=lang_switch()?><a href="logout.php"><?=e(t('nav.logout'))?></a></nav></header><main>
<section class="hero"><p class="eyebrow"><?=e(t('hero.eyebrow'))?></p><h1><?=e(t('hero.title'))?></h1><p><?=e(t('hero.body'))?></p></section>
<section id="api" class="panel"><div class="sectionhead"><div><h2>DeepSeek · BYOK</h2><p class="muted"><?=e(t('api.byok_note'))?></p></div><span id="keyBadge" class="badge warn"><?=e(t('api.key_missing'))?></span></div><div class="inline"><input id="apiKey" type="password" placeholder="sk-…" autocomplete="off" spellcheck="false"><button type="button" id="forgetKeyBtn"><?=e(t('api.forget'))?></button></div><div class="note"><strong><?=e(t('api.privacy_title'))?></strong> <?=e(t('api.privacy_body'))?></div></section>
<section id="mission" class="panel"><div class="sectionhead"><div><h2><?=e(t('mission.new'))?></h2><p class="muted"><?=e(t('mission.help'))?></p></div><span class="badge"><?=e(t('mission.contract',['version'=>ODLAB_VERSION]))?></span></div>
<div class="grid2"><label><?=e(t('mission.title'))?><input id="title" value="OD experiment"></label><label><?=e(t('mission.suite'))?><select id="suite"><option>smoke</option><option selected>core</option><option>h2</option><option>h3</option><option>h5</option><option>all</option><option>custom</option></select></label></div><label><?=e(t('mission.objective'))?><textarea id="objective" rows="3"><?=e(lang()==='fr'?'Comparer replay, recombinaison et alternatives model-relative sous admission absolue et rollback.':'Compare replay, recombination, and model-relative alternatives under absolute admission and rollback.')?></textarea></label>
<h3><?=e(t('section.mix'))?> <?=info_tip('mix')?></h3><div class="sliders">
<div class="slider"><label class="slider-label"><span class="labeltext"><?=e(t('mix.rho'))?> <?=info_tip('rho')?></span><output id="rhoOut">0.66</output></label><input id="rho" type="range" min="0" max="1" step="0.01" value="0.66"></div>
<div class="slider"><label class="slider-label"><span class="labeltext"><?=e(t('mix.cf'))?> <?=info_tip('cf')?></span><output id="cfOut">0.50</output></label><input id="cfshare" type="range" min="0" max="1" step="0.01" value="0.50"></div></div>
<div class="mixcards"><div><span><?=e(t('mix.alpha'))?></span><strong id="alpha"><?=number_format($mix['replay'],3)?></strong></div><div><span><?=e(t('mix.beta'))?></span><strong id="beta"><?=number_format($mix['recombination'],3)?></strong></div><div><span><?=e(t('mix.gamma'))?></span><strong id="gamma"><?=number_format($mix['counterfactual'],3)?></strong></div></div><p class="micro"><?=e(t('mix.backend'))?></p>
<h3><?=e(t('section.admission'))?></h3><div class="sliders">
<?=slider('param.candidates','candidates','candidateBudget','24','4','80','2','candidate_budget')?>
<?=slider('param.temperature','temperature','temperature','0.35','0.05','2','0.05','temperature')?>
<?=slider('param.lambda_n','lambda_n','noveltyWeight','1.0','0','4','0.1','novelty_weight')?>
<?=slider('param.lambda_c','lambda_c','coherenceWeight','0.5','0','4','0.1','coherence_weight')?>
<?=slider('param.eta','eta','memoryReplace','0.25','0','1','0.05','memory_replace_fraction')?>
<?=slider('param.delta_ret','delta_ret','gateRetention','0.05','0','0.30','0.01','gate_retention_tolerance')?>
<?=slider('param.delta_check','delta_check','gateCheck','0.05','0','0.30','0.01','gate_accuracy_tolerance')?>
</div><div class="note"><strong>λA.</strong> <?=e(t('anchor.note'))?></div>
<h3><?=e(t('section.budget'))?></h3><div class="sliders">
<?=slider('param.seeds','seeds','seedCount','1','1','10','1')?>
<?=slider('param.memory','memory','memoryCapacity','12','8','36','1')?>
<?=slider('param.api_calls','api_calls','maxApiCalls','120','20','500','10')?>
<?=slider('param.output_tokens','output_tokens','maxOutputTokens','100000','10000','300000','10000')?>
</div>
<div id="preflightCard" class="preflight-card"><span><?=e(t('preflight.label'))?></span><strong id="conditionCount"><?=e(t('preflight.conditions',['n'=>$preview['condition_count']]))?></strong><span id="apiEstimate"><?=e(t('preflight.calls',['base'=>$preview['estimated_api_calls']['baseline'],'worst'=>$preview['estimated_api_calls']['worst_case_attempts']]))?></span><span id="previewStatus" class="badge good"><?=e(t('preflight.valid'))?></span></div>
<div class="warning"><?=info_tip('final')?> <?=e(t('final.warning'))?></div><button class="primary" id="runBtn"><?=e(t('run.start'))?></button><div id="runStatus" class="status" aria-live="polite"></div></section>
<section class="panel research-contract"><div class="sectionhead"><div><h2><?=e(t('section.math'))?> <?=info_tip('math')?></h2><p class="muted"><?=e(t('math.summary'))?></p></div><span class="badge good">ODLAB-PHP-1.4</span></div><div class="mathgrid"><?php foreach($math as $item):?><article class="math-card"><header><h3><?=e($item['label'])?></h3><span class="badge <?=e($item['status'])?>"><?=e(t('math.'.$item['status']))?></span></header><p class="micro"><code><?=e($item['owner'])?></code><?php if(!empty($item['note'])):?><br><?=e($item['note'])?><?php endif?></p></article><?php endforeach?></div></section>
<section id="runs" class="panel"><div class="sectionhead"><div><h2><?=e(t('history.title'))?></h2><p class="muted"><?=e(t('history.help'))?></p></div></div><div class="tablewrap"><table><thead><tr><th><?=e(t('history.id'))?></th><th><?=e(t('history.mission'))?></th><th><?=e(t('history.suite'))?></th><th><?=e(t('history.status'))?></th><th><?=e(t('history.hash'))?></th><th><?=e(t('history.date_report'))?></th></tr></thead><tbody><?php foreach($missions as $m):?><tr><td><?=$m['id']?></td><td><?=e($m['title'])?></td><td><?=e($m['suite'])?></td><td><span class="badge <?=e($m['status'])?>"><?=e($m['status'])?></span></td><td><code><?=e(substr($m['config_hash'],0,12))?></code></td><td><?=e($m['created_at'])?><?php if(!empty($m['run_id'])):?><br><a href="report.php?id=<?=$m['run_id']?>"><?=e(t('history.report',['id'=>$m['run_id']]))?></a><?php endif?></td></tr><?php endforeach?></tbody></table></div></section></main>
<script>window.ODLAB_I18N=<?=json_encode($js,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;</script><script src="assets/app.js"></script></body></html>
