<?php
declare(strict_types=1);
require_once __DIR__.'/../app/bootstrap.php';require_login();
$id=(int)($_GET['id']??0);$run=(new ODLab\LabService())->getRun($id);if(!$run){http_response_code(404);die(e(t('error.run_not_found')));}
$a=$run['analysis'];$s=$a['summary']??[];$rows=$a['rows']??[];$conditions=$a['conditions']??[];$math=ODLab\ResearchContract::mathCoverage();
function pct($x):string{return$x===null?'n/a':number_format(100*(float)$x,1).'%';}
function num($x,int $d=3):string{return$x===null?'n/a':number_format((float)$x,$d);}
function ci_text($stats,bool $asPct=true):string{if(empty($stats['ci95']))return'n/a';$lo=$stats['ci95'][0];$hi=$stats['ci95'][1];return$asPct?pct($lo).' – '.pct($hi):num($lo).' – '.num($hi);}
function delta_card(array $x,bool $asPct=true):string{$st=$x['delta_stats']??[];$m=$st['mean']??null;$mean=$asPct?pct($m):num($m);return '<div class="mini"><span>'.e(t('report.delta')).'</span><strong>'.$mean.'</strong></div><p class="micro">'.e(t('report.ci95')).': '.e(ci_text($st,$asPct)).'<br>'.e(t('report.decision')).': '.e((string)($x['decision']??'n/a')).'</p>';}
$chartRows=[];foreach($conditions as $name=>$c)$chartRows[]=['name'=>$name,'ret'=>$c['retention']['mean'],'known'=>$c['known_transfer']['mean'],'abs'=>$c['absent_factor']['mean'],'admission'=>$c['admission_rate']['mean'],'novelty'=>$c['learning_novelty']['mean']??null];
function lswitch_report():string{$l=lang();return '<div class="langswitch"><a '.($l==='fr'?'class="active" ':'').'href="'.e(lang_url('fr')).'">FR</a><a '.($l==='en'?'class="active" ':'').'href="'.e(lang_url('en')).'">EN</a></div>';}
?><!doctype html><html lang="<?=e(lang())?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><link rel="stylesheet" href="assets/app.css"><title>OD Lab Report #<?=$id?></title></head><body><header><div><strong>OD Lab Report #<?=$id?></strong><span><?=e($run['title'])?></span></div><nav><a href="index.php"><?=e(t('nav.mission_control'))?></a><a href="export.php?id=<?=$id?>&format=json"><?=e(t('nav.research_json'))?></a><a href="export.php?id=<?=$id?>&format=csv"><?=e(t('nav.csv'))?></a><?=lswitch_report()?></nav></header><main>
<section class="hero"><p class="eyebrow"><?=e(t('report.eyebrow'))?></p><h1><?=e($run['title'])?></h1><p><?=e($run['objective'])?></p><p class="muted"><?=e(t('report.descriptive'))?></p><div class="note"><strong><?=e(t('report.analysis_status'))?>:</strong> <?=e((string)($a['research_status']??'n/a'))?> · <?=e((string)($a['research_status_note']??''))?></div></section>
<section class="metricgrid"><div><span><?=e(t('report.condition_runs'))?></span><strong><?=$s['condition_runs']??0?></strong></div><div><span><?=e(t('report.gates_pass'))?></span><strong><?=$s['gate_passes']??0?></strong></div><div><span><?=e(t('report.gates_fail'))?></span><strong><?=$s['gate_failures']??0?></strong></div><div><span><?=e(t('report.no_change'))?></span><strong><?=$s['no_change']??0?></strong></div><div><span><?=e(t('report.rollbacks'))?></span><strong><?=$s['rollbacks']??0?></strong></div><div><span><?=e(t('report.mean_ret'))?></span><strong><?=pct($s['mean_retention']??null)?></strong></div><div><span><?=e(t('report.known'))?></span><strong><?=pct($s['mean_known_transfer']??null)?></strong></div><div><span><?=e(t('report.absent'))?></span><strong><?=pct($s['mean_absent_factor']??null)?></strong></div></section>
<section class="panel"><div class="sectionhead"><div><h2><?=e(t('report.profile'))?></h2><p class="muted"><?=e(t('report.profile_help'))?></p></div></div><div class="chart" id="chart" data-rows='<?=e(json_encode($chartRows,JSON_UNESCAPED_SLASHES))?>' data-none="<?=e(t('chart.none'))?>" data-aria="<?=e(t('chart.aria'))?>" data-ret="<?=e(t('chart.ret'))?>" data-known="<?=e(t('chart.known'))?>" data-absent="<?=e(t('chart.absent'))?>"></div></section>
<section class="panel"><h2><?=e(t('report.aggregated'))?></h2><div class="cards"><?php foreach($conditions as $name=>$c):?><article class="condition-card"><h3><?=e($name)?></h3><div class="mini"><span><?=e(t('report.n'))?></span><strong><?=$c['n']?></strong></div><div class="mini"><span><?=e(t('report.retention'))?></span><strong><?=pct($c['retention']['mean'])?></strong></div><div class="mini"><span><?=e(t('report.transfer'))?></span><strong><?=pct($c['known_transfer']['mean'])?></strong></div><div class="mini"><span><?=e(t('report.absent'))?></span><strong><?=pct($c['absent_factor']['mean'])?></strong></div><div class="mini"><span><?=e(t('report.admission'))?></span><strong><?=pct($c['admission_rate']['mean'])?></strong></div><div class="mini"><span><?=e(t('report.tokens'))?></span><strong><?=num($c['tokens']['mean'],0)?></strong></div><?php if($c['known_transfer']['ci95']):?><p class="micro"><?=e(t('report.ci',['lo'=>pct($c['known_transfer']['ci95'][0]),'hi'=>pct($c['known_transfer']['ci95'][1])]))?></p><?php else:?><p class="micro"><?=e(t('report.no_ci'))?></p><?php endif?></article><?php endforeach?></div></section>
<section class="panel"><h2><?=e(t('report.hypotheses'))?></h2>
<div class="hypgrid">
<article><h3><?=e(t('report.h1'))?></h3><p><?=e(t('report.h1_body'))?></p><?php $h1=$a['h1']??[];$p1=$h1['recombination_vs_replay']??[];$p2=$h1['recombination_vs_augmentation']??[];?><h4><?=e(t('report.h1_pair'))?></h4><?=delta_card($p1['known_transfer']??[])?><p class="micro"><?=e(t('report.retention_delta'))?>: <?=e(ci_text(($p1['retention']['delta_stats']??[]),true))?> · <?=e((string)($p1['retention']['decision']??'n/a'))?></p><h4><?=e(t('report.h1_aug'))?></h4><?=delta_card($p2['known_transfer']??[])?></article>
<article><h3><?=e(t('report.h2'))?></h3><?php $hm=$a['h2']['models']??[];?><p><?=e(t('report.points',['n'=>count($a['h2']['points']??[])]))?></p><?php if(($hm['status']??'')==='model_comparison'):?><p class="micro"><?=e(t('report.h2_models',['flat'=>num($hm['flat']['aicc']??null),'linear'=>num($hm['linear']['aicc']??null),'quad'=>num($hm['quadratic']['aicc']??null)]))?></p><p class="micro"><?=e(t('report.h2_vertex',['vertex'=>num($hm['quadratic_vertex']??null),'candidate'=>!empty($hm['interior_inverted_u_candidate'])?t('report.yes'):t('report.no')]))?> · <?=e(t('report.h2_peak',['value'=>pct($hm['estimated_peak_gain']??null)]))?></p><?php $bs=$hm['bootstrap']??[];if(($bs['status']??'')==='ok'&& !empty($bs['vertex_ci95'])):?><p class="micro"><?=e(t('report.h2_bootstrap',['lo'=>num($bs['vertex_ci95'][0]),'hi'=>num($bs['vertex_ci95'][1]),'frac'=>pct($bs['interior_inverted_u_fraction']??null)]))?></p><?php endif;?><?php else:?><p class="micro"><?=e(t('report.h2_insufficient'))?></p><?php endif?></article>
<article><h3><?=e(t('report.h3'))?></h3><p><?=e(t('report.h3_body',['n'=>count($a['h3']??[])]))?></p></article>
<article><h3><?=e(t('report.h4'))?></h3><p><?=e(t('report.h4_pair'))?></p><?php $h4p=$a['h4']['primary_recombination_vs_replay']??[];?><p class="micro"><strong>ΔΔ</strong>: <?=pct($h4p['benefit_contrast']['mean']??null)?> · <?=e(t('report.ci95'))?> <?=e(ci_text($h4p['benefit_contrast']??[],true))?> · <?=e(t('report.decision'))?>: <?=e((string)($h4p['decision']??'n/a'))?></p><details><summary><?=e(t('report.h4_raw'))?></summary><?php foreach(($a['h4']['raw_within_condition_diagnostic']??[]) as $cond=>$h4):?><p class="micro"><strong><?=e($cond)?></strong>: <?=e(t('report.known_minus_absent'))?> <?=pct($h4['known_minus_absent']['mean']??null)?> · <?=e(ci_text($h4['known_minus_absent']??[],true))?></p><?php endforeach?></details></article>
<article><h3><?=e(t('report.h5'))?></h3><p><?=e(t('report.h5_body'))?></p><?=delta_card($a['h5']['known_transfer']??[])?><p class="micro"><?=e(t('report.h5_costs',['tokens'=>num($a['h5']['tokens']['delta_stats']['mean']??null,0),'api'=>num($a['h5']['api_calls']['delta_stats']['mean']??null,1),'wall'=>num($a['h5']['wall_seconds']['delta_stats']['mean']??null,3)]))?></p></article>
</div></section>
<section class="panel"><h2><?=e(t('report.analysis_plan'))?></h2><pre><?=e(json_encode($a['analysis_plan']??[],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))?></pre></section>
<section class="panel research-contract"><div class="sectionhead"><div><h2><?=e(t('section.math'))?> <?=info_tip('math')?></h2><p class="muted"><?=e(t('math.summary'))?></p></div></div><div class="mathgrid"><?php foreach($math as $item):?><article class="math-card"><header><h3><?=e($item['label'])?></h3><span class="badge <?=e($item['status'])?>"><?=e(t('math.'.$item['status']))?></span></header><p class="micro"><code><?=e($item['owner'])?></code><?php if(!empty($item['note'])):?><br><?=e($item['note'])?><?php endif?></p></article><?php endforeach?></div></section>
<section class="panel"><h2><?=e(t('report.evidence'))?></h2><div class="tablewrap"><table><thead><tr><th>condition</th><th>seed</th><th><?=e(t('report.ref_ret'))?></th><th><?=e(t('report.proposal_ret'))?></th><th><?=e(t('report.commit_ret'))?></th><th>known</th><th>absent</th><th><?=e(t('report.admitted_rejected'))?></th><th><?=e(t('report.gate'))?></th><th><?=e(t('report.eta'))?></th><th><?=e(t('report.tv'))?></th><th>API</th><th><?=e(t('report.tokens'))?></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['condition'])?></td><td><?=$r['seed']?></td><td><?=pct($r['reference_retention'])?></td><td><?=pct($r['proposal_retention'])?></td><td><?=pct($r['committed_retention'])?></td><td><?=pct($r['final_known_accuracy'])?></td><td><?=pct($r['final_absent_accuracy'])?></td><td><?=$r['admitted_count']?> / <?=$r['rejected_count']?></td><td><span class="badge <?=e($r['gate_status'])?>"><?=e($r['gate_status'])?></span></td><td><?=num($r['eta']??null,2)?></td><td><?=num($r['memory_tv_proposal_reference']??null,3)?></td><td><?=$r['usage']['api_calls']?></td><td><?=$r['usage']['input_tokens']+$r['usage']['output_tokens']?></td></tr><?php endforeach?></tbody></table></div></section>
<section class="panel"><h2><?=e(t('report.math_trace'))?></h2><p class="muted"><?=e(t('report.math_trace_help'))?></p><?php foreach($run['condition_evidence'] as $ce):$r=$ce['result']??[];$trace=$r['equation_trace']??[];?><details><summary><?=e(($r['condition']??'condition').' · '.t('report.seed').' '.($r['seed']??''))?></summary><pre><?=e(json_encode($trace,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))?></pre></details><?php endforeach?></section>
<section class="panel"><h2><?=e(t('report.trace'))?></h2><p class="muted"><strong><?=e(t('report.integrity'))?>.</strong> <?=e(t('report.hash_note'))?></p><div class="tracegrid"><div><span><?=e(t('report.evidence_integrity_label'))?></span><strong><?=!empty($run['integrity']['ok'])?'PASS':'FAIL'?></strong></div><div><span><?=e(t('report.evidence_root'))?></span><code><?=e((string)($run['evidence_root_sha256']??'n/a'))?></code></div><div><span><?=e(t('report.config_hash'))?></span><code><?=e($run['config_hash'])?></code></div><div><span><?=e(t('report.split_hash'))?></span><code><?=e($run['split_hash'])?></code></div><div><span><?=e(t('report.code_hash'))?></span><code><?=e($run['code_manifest_hash'])?></code></div><div><span><?=e(t('report.version'))?></span><code><?=e($run['software_version'])?></code></div><div><span><?=e(t('report.model'))?></span><code><?=e($run['provider_model'])?></code></div><div><span><?=e(t('report.paper_hash'))?></span><code><?=e($run['config']['research_contract']['paper_sha256']??'n/a')?></code></div><div><span><?=e(t('report.protocol'))?></span><code><?=e($run['config']['research_contract']['protocol_version']??'n/a')?></code></div><div><span><?=e(t('report.events'))?></span><strong><?=count($run['events'])?></strong></div></div><details><summary><?=e(t('report.frozen_config'))?></summary><pre><?=e(json_encode($run['config'],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))?></pre></details><details><summary><?=e(t('report.split_manifest'))?></summary><pre><?=e(json_encode($run['split_manifest'],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></pre></details><details><summary><?=e(t('report.event_log'))?></summary><pre><?=e(json_encode($run['events'],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))?></pre></details></section></main><script src="assets/report.js"></script></body></html>
